name: Publish

on:
  workflow_dispatch:

jobs:
  update-homebrew:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get latest release
        uses: actions/github-script@v3
        id: fetch_release_version
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: |
            const { data } = await github.repos.getRelease({
              owner: 'joachimdalen',
              repo: 'bicepdocs',
              release_id: 'latest',
            });
            return data.tag_name.substring(1);
      - name: Get checksum
        id: fetch_release_checksum
        run: |
          set -euxo pipefail
          result=$(curl -Lf https://github.com/joachimdalen/bicepdocs/releases/download/v${{ steps.fetch_release_version.outputs.result }}/bicepdocs-osx-x64 | sha256sum | awk '{print $1}')
          echo "::set-output name=result::$result"
      - name: Update formula
        run: |
          set -euxo pipefail
          export release_version="${{ steps.fetch_release_version.outputs.result }}"
          export release_sha256="${{ steps.fetch_release_checksum.outputs.result }}"
          envsubst < ./.github/workflows/bicepdocs.rb.tpl > ./Formula/bicepdocs.rb
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Bump formula to v${{ steps.fetch_release_version.outputs.result }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: update-homebrew
          delete-branch: true
          title: Bump formula to  v${{ steps.fetch_release_version.outputs.result }}
          draft: false